### PR TITLE
`r_base::<`

### PR DESCRIPTION
**Pull request by romainfrancois**
This probably needs a layer of abstraction, because this is very similar (and indeed copied from the `==` implementation). I'll abstract.

### CODE REVIEW

**Comment by romainfrancois** [comment]
This currently fails because string comparisons work differently, probably a locale issue ? 

``` r
library(duckdbrfuns)
library(DBI)
con <- duckdbrfuns:::con()

"tRue" < "TRUE"
#> [1] TRUE

dbGetQuery(con, r"(  SELECT 'tRue' < 'TRUE'  )")
#>   ('tRue' < 'TRUE')
#> 1             FALSE
dbGetQuery(con, r"(  SELECT "r_base::<"('tRue', 'TRUE')  )")
#>   r_base::<('tRue', 'TRUE')
#> 1                     FALSE

cpp11::cpp_eval('strcmp("tRue", "TRUE") < 0')
#> [1] FALSE
```

<sup>Created on 2024-02-09 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by romainfrancois** [comment]
This is indeed a locale/collate thing: 

``` r
Sys.getlocale("LC_COLLATE")
#> [1] "en_US.UTF-8"
"tRue" < "TRUE"
#> [1] TRUE

Sys.setlocale("LC_COLLATE", "C")
#> [1] "C"
"tRue" < "TRUE"
#> [1] FALSE
```

<sup>Created on 2024-02-09 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Review by krlmlr — COMMENTED** [review]
Thanks. I wonder what's going on with the tests, will investigate. Do we need locale-aware string comparison?

**Comment by krlmlr** [comment]
This PR breaks tests on CI/CD. I don't understand what's going on, but the main branch works consistently, and the PR fails consistently.

**Comment by romainfrancois** [comment]
I'll have a look first thing next week, or maybe on Friday. I also don't understand what is going on.

**Comment by krlmlr** [comment]
Works for me locally. A memory issue due to files too large? Trying something.

**Comment by krlmlr** [comment]
Could be a change to GHA. Running an empty PR to double-check.

**Comment by krlmlr** [comment]
Moving forward, let's do smaller PRs. 🐣

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
