### PR TITLE
initial pkg setup

### PR DESCRIPTION
**Pull request by romainfrancois**
So that we can: 

``` r
library(duckdb)
#> Loading required package: DBI
con <- duckdbrfuns:::con()
dbGetQuery(con, 'SELECT "r_base::+"(1, 2)')
#>   r_base::+(1, 2)
#> 1               3
```

<sup>Created on 2024-01-25 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

❓ perhaps the `make pkg` should be part of `make` 🤷

### CODE REVIEW

**Review by krlmlr — APPROVED** [review]
Thanks, a great start!

**Comment by romainfrancois** [comment]
This is basic, but at least we have a host for tools to generate tests automatically ... I'm not sure about `duckdbrfuns:::con()` but I'm also not too worried about it

**Comment by krlmlr** [comment]
Can't wait to test it myself!

**Comment by romainfrancois** [comment]
🚀 the `README` should help you. I'll merge so that I can play in a follow up PR.

**Comment by romainfrancois** [comment]
closes #5

**Pull request merged**
