### PR TITLE
attempt to test with testthat

### PR DESCRIPTION
**Pull request by romainfrancois**

### CODE REVIEW

**Comment by romainfrancois** [comment]
... and now I realise I did not see #10 ...

**Comment by krlmlr** [comment]
But that shouldn't be a conflict?

**Comment by romainfrancois** [comment]
> But that shouldn't be a conflict?

No, I think that just means we sync about it, it seems there are some things for me to learn in #10 💯

**Comment by romainfrancois** [comment]
I believe we can close this, and aim at a generative way as discussed in #11

**Pull request closed without merging**
